name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src

      - name: Find config directories
        id: find-configs
        run: |
          find config -name "default.nix" -type f -exec dirname {} \; | sed 's|^config/||' > configs.txt

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.05

      - uses: cachix/cachix-action@v14
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true

      - name: Build all firmwares
        continue-on-error: true
        run: |
          while IFS= read -r config; do
            echo "Building $config..."
            nix-build config/$config -o $config || echo "Failed to build $config"
            cp $config/glove80.uf2 $config.uf2 || echo "Failed to copy $config firmware"
          done < configs.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: firmwares
          path: "*.uf2"
